### ISSUE TITLE
yup-phone is not working with yup latest version (1.2.0)

### ISSUE THREAD

**Issue by sannjayy** [abhisekp/yup-phone#824]
Describe the bug
yup-phone is not working with this current version

getting: TypeError: yup__WEBPACK_IMPORTED_MODULE_5__.string(...).phone is not a function

To Reproduce
Try to validate phone number with yup-phone

const validate = Yup.object({
phone: Yup.string()
.phone("IN")
.required('Enter your valid mobile number.'),
})

NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

Expected behavior
Should validate the phone input field

Platform (please complete the following information):

Browser [All]
Version [latest]
Additional context

"next": "13.4.9",
"react": "18.2.0",
"react-dom": "18.2.0",
"formik": "^2.4.2",
"yup": "^1.2.0",
"yup-phone": "^1.3.2"

**Comment by simonmaass** [comment]
also getting Uncaught (in promise) TypeError: string(...).phone is not a function with nuxt 3 yup 1.2.0

**Comment by minotogna** [comment]
is this package maybe abandoned ?

**Comment by yosukapro** [comment]
Does any one have solution to use this package with latest version of Yup?

**Comment by simonmaass** [comment]
@abhisekp are you still maintaining this package? Thank you for all your work!

**Comment by abhisekp** [comment]
@simonmaass I'm not actively maintaining the package.

**Comment by sannjayy** [comment]
mobile: Yup.string().matches(/^[6-9]\d{9}$/, 'Invalid mobile number').required('Mobile number is required'),
